# Generated by Django 3.1 on 2021-02-02 20:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20210202_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='xabruser',
            name='like_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='кол-во'),
        ),
        migrations.AlterField(
            model_name='xabruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 20, 32, 37, 646188, tzinfo=utc)),
        ),
    ]
