# Generated by Django 3.1.5 on 2021-02-06 12:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0022_auto_20210206_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xabruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 12, 47, 44, 290820, tzinfo=utc)),
        ),
    ]
