# Generated by Django 3.1.5 on 2021-02-07 17:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0023_auto_20210206_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xabruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 17, 54, 17, 787547, tzinfo=utc)),
        ),
    ]
