# Generated by Django 3.1.5 on 2021-02-07 19:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0025_auto_20210207_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xabruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 19, 13, 14, 355132, tzinfo=utc)),
        ),
    ]
