# Generated by Django 3.1 on 2021-02-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0026_auto_20210204_2313'),
        ('authapp', '0013_auto_20210205_1831'),
    ]

    operations = [
    ]
