# Generated by Django 3.1 on 2021-02-06 09:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0027_merge_20210206_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xabruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 9, 30, 3, 901161, tzinfo=utc)),
        ),
    ]
