# Generated by Django 3.1 on 2021-02-05 20:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0029_auto_20210205_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xabruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 20, 18, 49, 159702, tzinfo=utc)),
        ),
    ]
