# Generated by Django 3.1 on 2021-02-05 21:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0033_auto_20210206_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xabruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 21, 6, 20, 906595, tzinfo=utc)),
        ),
    ]
