# Generated by Django 3.1 on 2021-02-05 21:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0036_auto_20210206_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xabruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 21, 17, 37, 637860, tzinfo=utc)),
        ),
    ]
