# Generated by Django 2.2 on 2021-01-27 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, unique=True, verbose_name='название категории')),
                ('slug', models.SlugField(default='', max_length=70, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='описание категории')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название статьи')),
                ('slug', models.SlugField(default='', max_length=70, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='краткое описание статьи')),
                ('posts_text', models.TextField(blank=True, verbose_name='текст статьи')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category')),
            ],
        ),
    ]
