# Generated by Django 2.2 on 2021-01-29 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, unique=True, verbose_name='название категории')),
                ('slug', models.SlugField(max_length=70, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='описание категории')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название статьи')),
                ('slug', models.SlugField(max_length=70, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='краткое описание статьи')),
                ('posts_text', models.TextField(blank=True, verbose_name='текст статьи')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('like_quantity', models.PositiveIntegerField(default=0, verbose_name='кол-во')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mainapp.Post')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
