# Generated by Django 2.2 on 2021-01-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XabrCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название категории')),
                ('description', models.TextField(blank=True, verbose_name='описание категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
        ),
    ]
