# Generated by Django 3.1.5 on 2021-01-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xabrcategory',
            name='is_active',
        ),
    ]
