# Generated by Django 2.2 on 2021-01-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xabrcategory',
            name='is_active',
        ),
    ]
