<<<<<<< Updated upstream:Xabr/mainapp/migrations/0002_auto_20210120_1144.py
# Generated by Django 3.1.5 on 2021-01-20 08:44
=======
# Generated by Django 3.1.5 on 2021-01-18 18:21
>>>>>>> Stashed changes:Xabr/mainapp/migrations/0002_auto_20210118_2121.py

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=1, max_length=64, unique=True, verbose_name='название категории'),
        ),
        migrations.AddField(
            model_name='post',
            name='create_datetime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата создания'),
            preserve_default=False,
        ),
    ]
