# Generated by Django 3.1 on 2021-02-04 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
