# Generated by Django 2.2 on 2021-01-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_xabrcategory_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xabrcategory',
            name='is_active',
        ),
    ]
