# Generated by Django 3.1 on 2021-02-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='text',
        ),
        migrations.AddField(
            model_name='likes',
            name='like_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='кол-во'),
        ),
    ]
