# Generated by Django 2.2 on 2021-01-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_xabrcategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='xabrcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активна'),
        ),
    ]
