# Generated by Django 3.1.5 on 2021-01-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210120_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, verbose_name='краткое описание статьи'),
        ),
    ]
