# Generated by Django 3.1 on 2021-02-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_comments_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('created',), 'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
    ]
