# Generated by Django 3.1 on 2021-01-31 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210131_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'комментировать', 'verbose_name_plural': 'комментарии'},
        ),
    ]
