# Generated by Django 3.1 on 2021-02-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210203_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='like_quantity',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='slug',
        ),
    ]
