# Generated by Django 3.1 on 2021-02-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210205_1831'),
        ('mainapp', '0002_post_likes'),
    ]

    operations = [
    ]
