# Generated by Django 3.1 on 2021-02-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_like_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активна'),
        ),
    ]
