# Generated by Django 3.1.5 on 2021-01-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, unique=True, verbose_name='URL'),
        ),
    ]
