# Generated by Django 3.1.5 on 2021-01-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
