# Generated by Django 3.1.5 on 2021-01-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20210124_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='slug', max_length=70, unique=True, verbose_name='URL'),
        ),
    ]
