# Generated by Django 3.1.5 on 2021-02-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210207_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=128, verbose_name='название статьи'),
        ),
    ]
