# Generated by Django 3.1.5 on 2021-01-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20210124_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=70, unique=True, verbose_name='URL'),
        ),
    ]
